services:
  - type: web
    name: waveiq
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: waveiq-db
          property: connectionString
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: waveiq-db
    databaseName: waveiq
    user: waveiq
    plan: free 